---
- hosts: freebsd
  become: yes
  tasks:
  - name: "Execute command!"
    command: /usr/bin/find /var/spool/clientmqueue -name '*' -delete
  - name: "Create Crontab"
    ansible.builtin.cron:
      name: "contab freebsd delete clientmqueue"
      minute: "0"
      weekday: "0"
      job: "/usr/bin/find /var/spool/clientmqueue -name '*' -delete"
      state: present
