---
- hosts: freebsd
  become: yes
  tasks:
  - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
    ansible.builtin.cron:
      name: "contab freebsd delete clientmqueue"
      minute: "0"
      day: "0"
      job: "/usr/bin/find /var/spool/clientmqueue -name '*' -delete"
      state: present
